### ISSUE TITLE
using the plugin offline?

### ISSUE THREAD

**Issue by bergarath** [lejmr/dokuwiki-plugin-drawio#14]
Hello.

I'm using pure local dokuwiki, with no internet access. I've a desktop installed version of draw.io .

But when I use the plugin, it always try to connect on the internet ... Any solution to use the local desktop version of draw.io?

thx !

**Comment by lejmr** [comment]
I am sorry I am not planning to make this plugin working offline. If you needs such a setup feel free to open a pull request.

I am afraid of consequences. Presume I would need to bundle and maintain 3rd party software in m github or so... I can imagine building a CI which would be creating such a package, but I am not interested. Feel free to fork this repository and maintain such a project.
