### ISSUE TITLE
Date in plugin.info.txt should be update at each release

### ISSUE THREAD

**Issue by dattaz** [lejmr/dokuwiki-plugin-drawio#17]
Cf https://www.dokuwiki.org/devel:plugin_info

https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/plugin.info.txt#L4

Otherwise Extension Manager indicates that an update is available even though we are already up to date.

**Comment by lejmr** [comment]
Thank you. I was wondering why is this happening! Will fix it and keep in my mind
