### ISSUE TITLE
Support for the ACL

### ISSUE THREAD

**Issue by kindlyfire** [lejmr/dokuwiki-plugin-drawio#2]
Hi there! This plugin is awesome, and adds a lot of value to DokuWiki.

That said, it is currently unusable on public wikis because it does not have support for the DokuWiki ACL. This means anyone (even when not logged in) can edit all the DrawIO images present on the wiki. I would like to know if support for the ACL is a feature we will see added?

**Comment by lejmr** [comment]
This would be a great functionality, but I am short of time. If you can, send me a pull request. Will be happy doing review and accepting it.
