### ISSUE TITLE
Unable to access documentation

### ISSUE THREAD

**Issue by TotalDaniel** [lejmr/dokuwiki-plugin-drawio#3]
i was attempting to access the documentation on your site https://lejmr.com ,however, the certificate is expired and i get a 502 error instead of your website

**Comment by lejmr** [comment]
Thank you for checking my personal web page.. I need to get it back working.. I was changing VPS provider. However, I tend to provide all documentation on DokuWiki page or possibly in the wiki here.

I will close this ticket, as my personal page is not related to this plugin. I double checked the https://www.dokuwiki.org/plugin:drawio there should be no link to lejmr.com page..

**Comment by 144132** [comment]
![image](https://user-images.githubusercontent.com/24652490/71806234-442fb080-30a3-11ea-88bc-617fbcc9f51d.png)

there is  https://lejmr.com link on https://github.com/lejmr/dokuwiki-plugin-drawio/

**Comment by lejmr** [comment]
Thank this is fixed now
