### ISSUE TITLE
Weblinks

### ISSUE THREAD

**Issue by Gerd88** [lejmr/dokuwiki-plugin-drawio#33]
Hello, I have draw.io installed.
You can create links, but they don't work.
Is it possible to create a link to internal pages, documents, etc. from draw.io?
Thanks for your help.

**Comment by lejmr** [comment]
The displayed digram is an PNG file actually. In other words, you can put as many links, but none of them will be clickable from the web page with the current implementation.

**Comment by lejmr** [comment]
Good news, somebody has been working on svg support which could potentially be a solution for you: https://github.com/lejmr/dokuwiki-plugin-drawio/pull/38
