### ISSUE TITLE
app.diagrams.net refused connection

### ISSUE THREAD

**Issue by Gerd88** [lejmr/dokuwiki-plugin-drawio#34]
Hello, I got following errors today. app.diagrams.net refused connection.
On the website comes following sign: app.diagrams.net will stop working for embed mode. Please use embed.diagrams.net.

Is there a solution for this problem?
Thx for the help.

**Comment by lejmr** [comment]
This plugins comes with a configuration option where you can set to URL from where the JS is loaded from.. just try to change the URL variable to "https://embed.diagrams.net" .. works for me. Probably I should change the default. Can you please send me PR. thanks

**Comment by lejmr** [comment]
https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/conf/default.php#L8

**Comment by Gerd88** [comment]
Hi, I changed the Website in the default.php and it works now.
Thx for the help.
