### ISSUE TITLE
Cannot create new diagrams

### ISSUE THREAD

**Issue by robertmooijman** [lejmr/dokuwiki-plugin-drawio#39]
I seem to have a problem where I can only edit existing diagrams on DW. I cannot get past to loading wheel when creating new ones. Anyone experiencing the same issue?

On a slightly related note: compatibilty with Firefox does not seem to be great... Cannot get the plugin to work at all on Firefox.

**Comment by whs92** [comment]
I can't open existing or new diagrams on any browser. maybe to do with https://www.diagrams.net/blog/move-diagrams-net

**Comment by fthommen** [comment]
Had the same issue yesterday but it works fine again today.  Maybe a temporary issue on diagrams.net?

I use the plugin w/o any problem with various versions of Firefox

**Comment by robertmooijman** [comment]
Today everything seems fine, indeed. Weird. Could be a temporary glitch as @fthommen suggests...
