### ISSUE TITLE
Firefox does not allow app.diagrams.net to open

### ISSUE THREAD

**Issue by 11ert** [lejmr/dokuwiki-plugin-drawio#40]
I used draw.io in my dokuwiki already successfully in the past. 
However, since a while I am not able to use it anymore. Whenever I click on the draw.io image to start editing the diagram, firefox tells me: "Firefox is not allowed to open the embedded page. For you security Firefox dows not allow app.diagrams.net to be opened....."
And Microsoft Edge just says: "apps.diagrams.net refused a connection"

I already de-installed the plug-in and installed the latest version but it does not help. Any idea?

**Comment by argorain** [comment]
Same here with Vivaldi. Actually first diagram went fine but after saving it I was unable to open it again or create new one, always ending with Connection refused.

**Comment by ninanoe** [comment]
Also does not work in Chrome.   It works in de old Internet Explorer lol,   Sure hope this gets fixed.

There is also an popup,  mentioning the url  app.diagrams.net  will stop working and needs to be   embed.diagrams.net

![draw](https://user-images.githubusercontent.com/4264513/99624370-7c777d80-2a2e-11eb-93af-0aa42c5489f2.png)

**Comment by ninanoe** [comment]
ok  fixed.     search for the   dokuwiki\lib\plugins\drawio\conf\   folder    and change the url in de default.php  file

Then it works

<?php
/*
 * default configuration settings
 * old=  $conf['url']       = 'https://www.draw.io';
 */

$conf['zIndex']    = 999;
$conf['url']       = 'https://embed.diagrams.net/';

**Comment by argorain** [comment]
Confirming. Changing it to `$conf['url']       = 'https://embed.diagrams.net';` solves this issue.

**Comment by argorain** [comment]
Hm, interestingly, this fix is already in there https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/conf/default.php but it wasn't installed 14th November when installed from dokuwiki plugin interface.
