### ISSUE TITLE
Question: Is the plugin conform to the General Data Protection Regulation?

### ISSUE THREAD

**Issue by Badeoel** [lejmr/dokuwiki-plugin-drawio#42]
In our company, we'd LOVE to use the draw.io-plugin in our intranet-Wiki. But for that, I have to confirm, that the plugin and draw.io is conform to the General Data Protection Regulation (EU, DSGVO in Germany) and does not exchange sensible data with other servers outside the intranet of the company. 

Can anybody please explain, where the data is stored and if it is transferred at any time to another server? 
This would help a lot!

**Comment by lejmr** [comment]
Look at the source code man! All the drawings are stored on you server exclusively, but I wouldn't bet a dime on any protection on the fly. On one hand, all the drawings happen on your computer, but...
