### ISSUE TITLE
Push Request: Change URL so embedded mode works again

### ISSUE THREAD

**Issue by CubaLibre84** [lejmr/dokuwiki-plugin-drawio#43]
Currently in Firefox I get this message:
"Firefox darf diese eingebettete Seite nicht öffnen".

I searched a bit and found this:
https://desk.draw.io/support/solutions/articles/16000042544-embed-mode

Important here:
**This mode is only supported on https://embed.diagrams.net.**

So I went into the Plugin /drawio/conf/defautl.php
and change the URL to:
`$conf['url']       = 'https://embed.diagrams.net';`

Can you please make this change ofr every user of the plugin available - currently I don't know how to make a proper pull request...

**Comment by lejmr** [comment]
Look here https://github.com/lejmr/dokuwiki-plugin-drawio/blob/master/conf/default.php#L8 this is already default for every user..
