### ISSUE TITLE
Location of drawio source file

### ISSUE THREAD

**Issue by awalkerca** [lejmr/dokuwiki-plugin-drawio#44]
Hello, I've got an internally hosted version of draw.io running and have successfully hooked it up to the plugin, thanks for making this easy.

I'm wondering where the drawio svg file is being saved. I have an existing draw.io diagram that I would like to move into my wiki. In using the "import" feature in draw.io, I can pull in my existing file but it won't save properly in the embedded context. My thought was that I might be able to copy the drawio file into the spot where it is saved, open it again via wiki plugin, and regenerate a new preview image - but I can't figure out where this location is.

I'd also like to make sure they are being backed properly such that I can easily upgrade my DokuWiki docker container, so if you could point me to where this lives in my DokuWiki data folder, that would be very helpful

**Comment by lejmr** [comment]
Hi and thank you :-)

Currently, as I have not managed to merge the svg support yet, all images are saved in .png format. 

If you place your draw.io-created images into data-dir along to your wiki pages, you should be able to even modify such an image. I know that sounds crazy, but It seems drawio stores some extra metadata even to png file, so it is editable. I tested it some time ago, and it worked for me
