### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by Gerd88** [lejmr/dokuwiki-plugin-drawio#47]
After updating draw.io I get following failure.

File name format or extension error: should be filename.extension (available extension :png)

How I can solve this failure?

Thx for the help.

**Comment by lejmr** [comment]
Look into plugin configuration and make sure the the _toolbar_possible_extension_ configuration has png in it.

**Comment by Gerd88** [comment]
Where can I find the toolbar_possible_extension file?
