### ISSUE TITLE
Plugin is not working when dokuwiki is installed in a subdirectory

### ISSUE THREAD

**Issue by jbarotin** [lejmr/dokuwiki-plugin-drawio#5]
Hi,

Fantastic plugin you've done here.

I installed on my instance of dokuwiki which I can access though an url like this : http://mydomain/dokuwiki/ 

Draw.io edit works very well and images are well stored in media, but image url generated on the wiki page looked like this http://mydomain/lib/exe/fetch.php?media=wiki:test|test.png. 

It doesn't works, it should be http://mydomain/dokuwiki/lib/exe/fetch.php?media=wiki:test|test.png

Could you fix that ?

ps : I did the the following workaround in `syntax.php` file: 
```
 $renderer->doc .= "<img class='mediacenter' id='".trim($data)."' 
                        style='max-width:100%;cursor:pointer;' 
                        onclick='edit(this);' 
                        src='http://mydomain/dokuwiki/lib/exe/fetch.php?media=".$data.".png' 
                        alt='".$file_name."' />";
```

But it's ugly :)

**Comment by chrisisbd** [comment]
I think the 'correct' fix is as follows:-

`
        $renderer->doc .= "<img class='mediacenter' id='".trim($data)."'  
                        style='max-width:100%;cursor:pointer;'  
                        onclick='edit(this);'  
                        src='".DOKU_BASE."lib/exe/fetch.php?media=".$data.".`
`

**Comment by chrisisbd** [comment]
Try again, the 'code' quotes don't seem to work too well:-

'''
`
        $renderer->doc .= "<img class='mediacenter' id='".trim($data)."'  
                        style='max-width:100%;cursor:pointer;'  
                        onclick='edit(this);'  
                        src='".DOKU_BASE."lib/exe/fetch.php?media=".$data.".
                        alt='".$file_name."' />";
'''

**Comment by chrisisbd** [comment]
Oh, I give up, I think it's clear what's intended.

**Comment by lejmr** [comment]
Can you please send me the fix in the form of a pull request? Thank you

**Comment by chrisisbd** [comment]
I'm trying but I find git very difficult (I'm a mercurial enthusiast).  I have got as far as creating a fork on github at chris/dokuwiki-plugin-drawio and I have changed syntax.php and have commited the change to my fork.  Try as I may though I can't get to work out how to actually create the pull request between my fork and your code.

Can you do that maybe, or tell me how to do it?

**Comment by lejmr** [comment]
I have just created the #6 for you..
